variables:
  SCRIPT_DIR: ".pipelines/scripts"

pool:
  vmImage: 'Ubuntu-16.04'

stages:

- stage: CodeQualityChecks
  jobs:
  - job: Lint_Code
    displayName: Lint Code
    steps:
    - bash: yarn
    - bash: yarn lint

  - job: Test_Code
    displayName: Test Code
    steps:
    - bash: yarn
    - bash: yarn test


- stage: SecurityChecks
  condition: >
    or(
      eq(variables['Build.SourceBranch'], 'refs/heads/master'), 
      startsWith(variables['Build.SourceBranch'], 'refs/heads/feature/'), 
      startsWith(variables['Build.SourceBranch'], 'refs/heads/fix/'), 
      startsWith(variables['Build.SourceBranch'], 'refs/heads/cleanup/'),
      not(startsWith(variables['Build.SourceBranch'], 'refs/heads/feature/experimental'))
    )
  jobs:
  - job: Code_Analysis
    displayName: Static Source Code Analysis (nodejsscan)
    steps:
    - bash: ./$(SCRIPT_DIR)/ssca.sh
  - job: Dep_Audit
    displayName: Audit Dependencies (yarn audit)
    steps:
    - bash: yarn
    - bash: yarn audit
  - job: Key_check
    displayName: Check for any committed keys (gitleaks)
    steps:
    - bash: ./$(SCRIPT_DIR)/check-leaks.sh


# die on an invalid branch name
- stage: BranchChecks # en
  condition: >
    not(or(
      eq(variables['Build.SourceBranch'], 'refs/heads/master'), 
      eq(variables['Build.SourceBranch'], 'refs/heads/develop'), 
      eq(variables['Build.SourceBranch'], 'refs/heads/staging'), 
      startsWith(variables['Build.SourceBranch'], 'refs/heads/feature/'), 
      startsWith(variables['Build.SourceBranch'], 'refs/heads/fix/'), 
      startsWith(variables['Build.SourceBranch'], 'refs/heads/cleanup/')
    ))
  jobs:
  - job: fail
    steps:
    - bash: echo Incorrect branch name. Please use a standard branch
    - bash: echo master, develop, staging, or a branch beginning with feature/, fix/ or cleanup/
    - bash: exit 1
