# [1] https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema
pr: 
- none
trigger:
- master

# Each stage has it's own container - 
# if you change something in one stage, it doesn't do anything for the other stage
stages:

# Start with checking the code and running all tests
- stage: Prod_CodeQuality
  jobs: 
  - job: Testing
    displayName: 📚 - Testing Code
    steps:
      - bash: echo [ETS] Testing code...
      - bash: yarn
      - bash: yarn test
- stage: Prod_Security
  jobs: 
  - job: Audit
    displayName: 🔐 - Auditing Dependencies
    continueOnError: true
    steps:
      - bash: yarn audit
