# [1] https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema
pr:
- feature/*

variables:
  BUILD_UNIQUE_ID: "$(Build.Repository.ID)-$(Build.BuildId)-$(Build.SourceBranchName)"
  YARN_CACHE_FOLDER: $(Pipeline.Workspace)/.yarn

# Each stage has it's own container - 
# if you change something in one stage, it doesn't do anything for the other stage
stages:
# Start with checking the code and running all tests
- stage: weird
  jobs:
  - job: Send_init
    steps:
    - bash: yarn add request request-promise
    - bash: node .pipelines/send-result.js $(SERVER_URL) init $(BUILD_UNIQUE_ID) $(Build.SourceBranchName) "$(date +%s)"
- stage: PR_CodeQuality
  jobs: 
  - job: TSLint
    displayName: 🧹 - Running TSLint
    steps:
      - task: CacheBeta@0
        inputs:
          key: yarn | $(Agent.OS) | yarn.lock
          path: $(YARN_CACHE_FOLDER)
      - script: yarn
      - bash: echo [ETS] Attempting to run linter...
      - bash: yarn lint
  - job: Testing
    displayName: 📚 - Testing Code
    steps:
      - task: CacheBeta@0
        inputs:
          key: yarn | $(Agent.OS) | yarn.lock
          path: $(YARN_CACHE_FOLDER)
      - bash: yarn test
- stage: PR_Test
  jobs: 
  - job: Testing
    displayName: TEST PLS
    steps:
      - bash: echo $(Build.BuildId) 
      - bash: echo $(Build.Repository.ID) 
      - bash: echo $(Build.Repository.Name)
  - job: Send_a_result
    displayName: phoning home
    steps:
    - bash: yarn add request request-promise
    - bash: node .pipelines/send-result.js $(SERVER_URL) phone $(BUILD_UNIQUE_ID) $(Build.SourceBranchName) "some more results"
- stage: PR_Security
  jobs: 
  - job: StaticAnalysis
    displayName: 🔎 - Analysing Source Code
    steps:
      - bash: ./.pipelines/ssca.sh
  - job: Leaks
    displayName: 🔑 - Checking for committed keys
    steps:
      - bash: ./.pipelines/check-leaks.sh
- stage: PR_End
  jobs:
  - job: SendEnd
    steps:
    - bash: yarn add request request-promise
    - bash: node .pipelines/send-result.js $(SERVER_URL) end $(BUILD_UNIQUE_ID) $(Build.SourceBranchName) "$(date +%s)"
