# [1] https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema
trigger: none

pr:
  branches:
    include:
      - feature/*
      - fix/*
      - cleanup/*
    exclude:
      - experimental/*
      - master
stages:
- stage: PR_CodeQuality
  jobs: 
  - job: TSLint
    displayName: 🧹 - Running TSLint
    continueOnError: true # todo: change this one pipeline has been established
    steps: 
      - bash: echo [ETS] Attempting to run linter...
      - bash: yarn
      - bash: yarn lint
  - job: Testing
    displayName: 📚 - Testing Code
    continueOnError: true
    steps:
      - bash: echo [ETS] Testing code...
      - bash: yarn
      - bash: yarn test
- stage: PR_Security
  condition: succeeded('CodeQuality')
  jobs: 
  - job: Audit
    displayName: 🔐 - Auditing Dependencies
    steps:
      - bash: yarn audit
  - job: StaticAnalysis
    displayName: 🔎 - Analysing Source Code
    steps:
      - bash: ./.pipelines/ssca.sh
  - job: Leaks
    displayName: 🔑 - Checking for committed keys
    steps:
      - bash: ./.pipelines/check-leaks.sh
