# [1] https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema
pr:
- feature/*

# Each stage has it's own container - 
# if you change something in one stage, it doesn't do anything for the other stage
stages:
# Start with checking the code and running all tests
- stage: PR_CodeQuality
  jobs: 
  - job: TSLint
    displayName: 🧹 - Running TSLint
    steps: 
      - bash: echo [ETS] Attempting to run linter...
      - bash: yarn
      - bash: yarn lint
  - job: Testing
    displayName: 📚 - Testing Code
    steps:
      - bash: echo [ETS] Testing code...
      - bash: yarn
      - bash: yarn test
- stage: PR_Test
  jobs: 
  - job: Testing
    displayName: TEST PLS
    steps:
      - bash: echo $(Build.BuildId) $(Environment.Name) $(Environment.ResourceName) $(Environment.Resourceid)
- stage: PR_Security
  jobs: 
  - job: StaticAnalysis
    displayName: 🔎 - Analysing Source Code
    steps:
      - bash: ./.pipelines/ssca.sh
  - job: Leaks
    displayName: 🔑 - Checking for committed keys
    steps:
      - bash: ./.pipelines/check-leaks.sh
